sudo: false
language: ruby

gemfile:
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - jruby-19mode
  - jruby-head

matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: jruby-head
